// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services (interfaces: IBalancer)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_services_balancer.go -package=mocks ./internal/services IBalancer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/aleksandrpnshkn/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIBalancer is a mock of IBalancer interface.
type MockIBalancer struct {
	ctrl     *gomock.Controller
	recorder *MockIBalancerMockRecorder
	isgomock struct{}
}

// MockIBalancerMockRecorder is the mock recorder for MockIBalancer.
type MockIBalancerMockRecorder struct {
	mock *MockIBalancer
}

// NewMockIBalancer creates a new mock instance.
func NewMockIBalancer(ctrl *gomock.Controller) *MockIBalancer {
	mock := &MockIBalancer{ctrl: ctrl}
	mock.recorder = &MockIBalancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBalancer) EXPECT() *MockIBalancerMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockIBalancer) GetBalance(ctx context.Context, user models.User) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, user)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIBalancerMockRecorder) GetBalance(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIBalancer)(nil).GetBalance), ctx, user)
}

// GetWithdrawals mocks base method.
func (m *MockIBalancer) GetWithdrawals(ctx context.Context, user models.User) ([]models.BalanceChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, user)
	ret0, _ := ret[0].([]models.BalanceChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockIBalancerMockRecorder) GetWithdrawals(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockIBalancer)(nil).GetWithdrawals), ctx, user)
}

// Withdraw mocks base method.
func (m *MockIBalancer) Withdraw(ctx context.Context, orderNumber string, amountRaw float64, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, orderNumber, amountRaw, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIBalancerMockRecorder) Withdraw(ctx, orderNumber, amountRaw, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIBalancer)(nil).Withdraw), ctx, orderNumber, amountRaw, user)
}
