// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handlers (interfaces: OrdersService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_orders_service.go -package=mocks ./internal/handlers OrdersService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/aleksandrpnshkn/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersService is a mock of OrdersService interface.
type MockOrdersService struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersServiceMockRecorder
	isgomock struct{}
}

// MockOrdersServiceMockRecorder is the mock recorder for MockOrdersService.
type MockOrdersServiceMockRecorder struct {
	mock *MockOrdersService
}

// NewMockOrdersService creates a new mock instance.
func NewMockOrdersService(ctrl *gomock.Controller) *MockOrdersService {
	mock := &MockOrdersService{ctrl: ctrl}
	mock.recorder = &MockOrdersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersService) EXPECT() *MockOrdersServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOrdersService) Add(ctx context.Context, orderNumber string, user models.User) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, orderNumber, user)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockOrdersServiceMockRecorder) Add(ctx, orderNumber, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOrdersService)(nil).Add), ctx, orderNumber, user)
}

// GetUserOrders mocks base method.
func (m *MockOrdersService) GetUserOrders(ctx context.Context, user models.User) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, user)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrdersServiceMockRecorder) GetUserOrders(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrdersService)(nil).GetUserOrders), ctx, user)
}

// HasProcessedStatus mocks base method.
func (m *MockOrdersService) HasProcessedStatus(order models.Order) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProcessedStatus", order)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProcessedStatus indicates an expected call of HasProcessedStatus.
func (mr *MockOrdersServiceMockRecorder) HasProcessedStatus(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProcessedStatus", reflect.TypeOf((*MockOrdersService)(nil).HasProcessedStatus), order)
}

// UpdateAccrual mocks base method.
func (m *MockOrdersService) UpdateAccrual(ctx context.Context, order models.Order) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccrual", ctx, order)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccrual indicates an expected call of UpdateAccrual.
func (mr *MockOrdersServiceMockRecorder) UpdateAccrual(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccrual", reflect.TypeOf((*MockOrdersService)(nil).UpdateAccrual), ctx, order)
}
