// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services (interfaces: IAccrualService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_services_accrual_service.go -package=mocks ./internal/services IAccrualService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockIAccrualService is a mock of IAccrualService interface.
type MockIAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockIAccrualServiceMockRecorder
	isgomock struct{}
}

// MockIAccrualServiceMockRecorder is the mock recorder for MockIAccrualService.
type MockIAccrualServiceMockRecorder struct {
	mock *MockIAccrualService
}

// NewMockIAccrualService creates a new mock instance.
func NewMockIAccrualService(ctrl *gomock.Controller) *MockIAccrualService {
	mock := &MockIAccrualService{ctrl: ctrl}
	mock.recorder = &MockIAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccrualService) EXPECT() *MockIAccrualServiceMockRecorder {
	return m.recorder
}

// GetAccrual mocks base method.
func (m *MockIAccrualService) GetAccrual(ctx context.Context, orderNumber string) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccrual indicates an expected call of GetAccrual.
func (mr *MockIAccrualServiceMockRecorder) GetAccrual(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrual", reflect.TypeOf((*MockIAccrualService)(nil).GetAccrual), ctx, orderNumber)
}
